version: '3'

services:
  common:
    build:
      context: ./docker
      dockerfile: Dockerfile.op-stack
    volumes:
      - ./op-stack-deployer:/app
    working_dir: /app
    networks:
      - op-network

  build-optimism:
    extends:
      service: common
    command: go run cmd/1_build_optimism/main.go

  build-op-geth:
    extends:
      service: common
    command: go run cmd/2_build_op-geth/main.go

  generate-keys:
    extends:
      service: common
    command: go run cmd/3_generate_keys/main.go
  
  Configure-network:
    extends:
      service: common
    command: go run cmd/4_configure_network/main.go

  deploy-l1-contracts:
    extends:
      service: common
    command: go run cmd/5_deploy_L1_contracts/main.go

  l2-config:
    extends:
      service: common
    command: sudo go run cmd/6_L2_config/main.go

  init-op-geth:
    extends:
      service: common
    command: go run cmd/7_Initialize_op-geth/main.go

  run-op-geth:
    extends:
      service: common
    command: go run cmd/8_run_op-geth/main.go

  run-op-node:
    extends:
      service: common
    command: go run cmd/9_run_op-node/main.go

  run-op-batcher:
    extends:
      service: common
    command: go run cmd/10_run_op-batcher/main.go

  run-op-proposer:
    extends:
      service: common
    command: go run cmd/11_run_op-proposer/main.go

networks:
  op-network:
