FROM golang:alpine

WORKDIR /app

COPY Dockerfile.build-op-geth /app/
COPY scripts/entrypoint-build-op-geth.sh /app/

RUN chmod +x /app/entrypoint-build-op-geth.sh

CMD ["/app/entrypoint-build-op-geth.sh"]