# Use the official Go image as the base image
FROM golang:alpine AS run-op-node

# Set the working directory inside the container
WORKDIR /app

# Copy the source code for 9_run_op-node
COPY cmd/9_run_op-node /app/

# Define the command to run when the container starts
CMD ["go run cmd/9_run_op-node/main.go "]
