FROM golang:alpine

WORKDIR /app

COPY Dockerfile.generate-keys /app/
COPY scripts/entrypoint-generate-keys.sh /app/

RUN chmod +x /app/entrypoint-generate-keys.sh

CMD ["/app/entrypoint-generate-keys.sh"]