FROM golang:alpine

WORKDIR /app

COPY Dockerfile.get-rollup-address /app/
COPY scripts/entrypoint-get-rollup-address.sh /app/

RUN chmod +x /app/entrypoint-get-rollup-address.sh

CMD ["/app/entrypoint-get-rollup-address.sh"]