# Use the official Go image as the base image
FROM golang:alpine AS run-op-batcher

# Set the working directory inside the container
WORKDIR /app

# Copy the source code for 10_run_op-batcher
COPY cmd/10_run_op-batcher /app/

# Define the command to run when the container starts
CMD ["go run cmd/10_run_op-batcher/main.go "]
