FROM golang:alpine

WORKDIR /app

COPY Dockerfile.build-optimism /app/
COPY scripts/entrypoint-build-optimism.sh /app/
COPY cmd /app/
COPY docker-compose /app/
COPY go.mod /app/
COPY go.sum /app/

RUN apk update && apk add --no-cache git nodejs npm make jq direnv

RUN chmod +x /app/entrypoint-build-optimism.sh

CMD ["/app/entrypoint-build-optimism.sh"]