FROM golang:alpine

WORKDIR /app

COPY Dockerfile.init-op-geth /app/
COPY scripts/entrypoint-init-op-geth.sh /app/

RUN chmod +x /app/entrypoint-init-op-geth.sh

CMD ["/app/entrypoint-init-op-geth.sh"]